version: 0.2

applications:
  - appRoot: client
    frontend:
      phases:
        preBuild:
          commands:
            - echo "Desactivando integración con secretos"
        build:
          commands:
            - echo "Construyendo frontend"

artifacts:
  files:
    - '**/*'  # Incluye todos los archivos generados en el proceso de construcción
  baseDirectory: client/build  # Aquí debes colocar la carpeta que contiene los archivos generados del frontend
