version: 0.2

phases:
  preBuild:
    commands:
      - echo "Iniciando construcción del proyecto"
  build:
    commands:
      - echo "Construyendo frontend"
      - cd client
      - npm install
      - npm run build
  postBuild:
    commands:
      - echo "Finalizando construcción"

artifacts:
  files:
    - '**/*'  # Esto asegura que todos los archivos generados durante la construcción se incluyan como artefactos
  baseDirectory: client/build  # Directorio donde se guardan los archivos generados por el frontend
